//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuildfordBoroughCouncil.Address.Api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AUTHORITY
    {
        public int AUTHORITY_REF { get; set; }
        public string AUTHORITY_NAME { get; set; }
        public int MINUSRN { get; set; }
        public int MAXUSRN { get; set; }
    }
}
