//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuildfordBoroughCouncil.Address.Api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BluelightEntities : DbContext
    {
        public BluelightEntities()
            : base("name=BluelightEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BLPU> BLPUs { get; set; }
        public virtual DbSet<AUTHORITY> AUTHORITies { get; set; }
    
        public virtual ObjectResult<DAL_GetAbbreviations_Result> DAL_GetAbbreviations()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DAL_GetAbbreviations_Result>("DAL_GetAbbreviations");
        }
    
        public virtual int SearchPropertyWithOptions(string searchToken, string searchOptions, Nullable<int> iRowsReturned)
        {
            var searchTokenParameter = searchToken != null ?
                new ObjectParameter("SearchToken", searchToken) :
                new ObjectParameter("SearchToken", typeof(string));
    
            var searchOptionsParameter = searchOptions != null ?
                new ObjectParameter("SearchOptions", searchOptions) :
                new ObjectParameter("SearchOptions", typeof(string));
    
            var iRowsReturnedParameter = iRowsReturned.HasValue ?
                new ObjectParameter("iRowsReturned", iRowsReturned) :
                new ObjectParameter("iRowsReturned", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SearchPropertyWithOptions", searchTokenParameter, searchOptionsParameter, iRowsReturnedParameter);
        }
    }
}
